### ISSUE TITLE
Updating hosted workflow/tools doesn't reset file after first cancellation (UI only issue)

### ISSUE THREAD

**Issue by Richard-Hansen** [dockstore/dockstore#4027] opened 2021-02-03 18:07 UTC
**Describe the bug**
Minor bug when editing a file for a hosted workflow or tool, the file edit UI won't reset to the pre-edit version of the file if you cancel a second time. This isn't sent over to the webservice, so if you refresh the page the file loads in its original, un-edited state. 

**To Reproduce**
1. Go to your workflows tab.
2. Navigate to, or create a hosted workflow.
3. Go to the files tab.
4. Select 'add file'.
5. Save as a new version.
6. Click the 'edit' button, type in some content, and hit cancel.
7. See that the file reverted to its original state.
8. Click 'edit' a second time, type in some content, and hit cancel.
9. See that the file kept the text that was just added.
10. All future cancels will now no longer revert local changes.

**Expected behavior**
When hitting cancel, all local changes should be removed.

**Screenshots**
First time hitting the 'cancel' button
<img width="284" alt="Screen Shot 2021-02-03 at 1 03 33 PM" src="https://user-images.githubusercontent.com/36607471/106789451-49518d00-6620-11eb-9745-459d3f9c79d8.png">
<img width="253" alt="Screen Shot 2021-02-03 at 1 03 40 PM" src="https://user-images.githubusercontent.com/36607471/106789466-4bb3e700-6620-11eb-9ab4-98a7d731af2f.png">
Second time hitting the 'cancel' button
<img width="299" alt="Screen Shot 2021-02-03 at 1 04 28 PM" src="https://user-images.githubusercontent.com/36607471/106789559-65edc500-6620-11eb-9615-c38f35cfbbad.png">
<img width="264" alt="Screen Shot 2021-02-03 at 1 03 48 PM" src="https://user-images.githubusercontent.com/36607471/106789475-4e164100-6620-11eb-9831-85b8ce8b48dd.png">

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.10.0) - 1.10.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.7) - 2.7

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.1) - 1.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.1) - 1.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1703)
┆Issue Number: DOCK-1703
┆Sprint: Backlog
┆Issue Type: Story

**Comment by NatalieEO** [comment] 2021-02-03 19:08
duplicate of #3800

**Closed by NatalieEO** 2021-02-03 19:08 UTC
Labels: bug
