### ISSUE TITLE
GitHub Apps Workflow: pushing branch with fixed descriptor still shows as invalid

### ISSUE THREAD

**Issue by GFJHogue** [dockstore/dockstore#3966] opened 2020-12-07 18:40 UTC
**Describe the bug**
For a GitHub Apps workflow, if we have an invalid branch (ex. broken WDL), and then we push a fix to that branch to make it valid (fixed WDL), the WorkflowVersion for that branch on Dockstore still shows as "invalid" (even showing the fixed WDL).

**To Reproduce**
1. Fork https://github.com/GFJHogue/long-read-pipelines/ (feel free to ignore LFS and delete `/.git/hooks/*` stuff)
2. Install Dockstore (staging) GitHub App to forked repo
3. Checkout https://github.com/GFJHogue/long-read-pipelines/commit/7d656cd65be2e96754a76979b9d17f3eac5c6743
4. Create a new branch and push (should appear on Dockstore as invalid with broken WDL)
5. Merge https://github.com/GFJHogue/long-read-pipelines/commit/09749261c9c81ee5891836d4ce7a3e11b0d61c0c into your branch (should appear on Dockstore as invalid with fixed WDL (**bug**))
6. Create a new tag at the previous merge commit and push (should appear on Dockstore as valid (**expected**))

**Expected behavior**
Branches that were invalid (had broken descriptors) and were fixed should appear valid on Dockstore.
- Valid checkmark should appear for branch in versions tab
- Should be able to publish workflow (button not disabled)

**Additional context**
 - Webservice version: 1.10.0
 - UI version: 2.7
 - host location: Prod, Staging

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1665)
┆Issue Number: DOCK-1665
┆Sprint: Backlog
┆Issue Type: Story

**Comment by NatalieEO** [comment] 2020-12-07 19:38
duplicate of #3812

**Closed by NatalieEO** 2020-12-07 19:38 UTC
Labels: bug, gui, web-service
