### ISSUE TITLE
Cannot add checker workflow to published WDL

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4436] opened 2021-08-31 21:53 UTC
**Describe the bug**
The analysis pipeline repo has several WDLs managed by a .dockstore.yml and several checker workflows which get manually refreshed. I recently merged @avani-k's KING workflow to main. Problem is, I can't add a checker workflow to it.

If I view the public page, a "ghost" checker workflow entry exists, but it does not have a valid descriptor file. Unpublishing this workflow leads to another issue: #4437 

<img width="1309" alt="screenshot_2021-08-31_at_1 21 54_pm" src="https://user-images.githubusercontent.com/27784612/131580477-6e5a784d-4d42-45a7-9316-5a84afe44205.png">

**Expected behavior**
All workflows and tools should allow me to add a checker.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1898)
┆Issue Number: DOCK-1898
┆Sprint: Backlog
┆Issue Type: Story

**Comment by Richard-Hansen** [comment] 2021-09-01 17:08
The issue seems to be caused by owning the parent workflow, while not being marked as an owner of the linked checker workflow. Because you are not owner of the checker workflow, the observable [checkerWorkflowURL$](https://github.com/dockstore/dockstore-ui2/blob/4d959368cc5359ac46376922e4c5b811305e3296/src/app/shared/entry/info-tab-checker-workflow-path/info-tab-checker-workflow-path.component.html#L11) in the linked statement does note evaluate correctly (looks to be empty), and so no icons appears for the `Checker Workflow:` row of the info tab.

@aofarrel if you were to obtain ownership of the linked checker workflow, you should be able to see the view icon. 

To reproduce locally:
1. Locate a workflow with a linked checker, that I'm an owner of (or a workflow with no linked checker, in this case, skip to step 3)
2. Remove the linked checker workflow from my local database, this allowed me to see the `+ add` icon for the parent workflow again.
3. Add a checker workflow that I do not own to the parent workflow. No icons appear for the row, just like the image in the original screenshot.
4. Obtain ownership of the checker workflow and refresh the page. I'm now able to see the `view` icon, as expected.

**Comment by coverbeck** [comment] 2021-09-01 17:58
* What are the two workflows on GitHub?
* What are the two workflows in Dockstore? I know, the should be the same, but maybe with renaming/transferring, they're not.

**Comment by avani-k** [comment] 2021-09-01 18:05
On GitHub:
[Here](https://github.com/DataBiosphere/analysis_pipeline_WDL/blob/main/king/king.wdl) is the king.wdl workflow
[Here](https://github.com/DataBiosphere/analysis_pipeline_WDL/blob/main/king/checker/king-checker.wdl) is the king-checker.wdl checker workflow

On Dockstore:
[Here](https://dockstore.org/workflows/github.com/DataBiosphere/analysis_pipeline_WDL/king-wdl:main?tab=info) is the king workflow
And [here](https://dockstore.org/workflows/github.com/DataBiosphere/analysis_pipeline_WDL/king-wdl_wdl_checker:main?tab=info) is the associated checker workflow

**Comment by Richard-Hansen** [comment] 2021-09-01 20:07
Solved. The checker workflow needed to be 'rediscovered' by Dockstore. This is accomplished by clicking the `Discover Existing Dockstore Workflows` button in the ui (drop down menu for the My Workflows tab on the left). This will discover proper ownership for Dockstore entries.

The UI's response to this ownership issue is still slightly odd, so I've linked a followup issue.

Will close this issue for now, feel free to re-open if it's not fully resolved.

**Closed by Richard-Hansen** 2021-09-01 20:07 UTC
Labels: bug, web-service, gui
