### ISSUE TITLE
Cannot remove or refresh a workflow with no descriptor file

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#5138] opened 2022-09-20 18:44 UTC
**Describe the bug**
While trying to replicate #4437 with Charles, I realized that same repo has a different ghost workflow. (I'm using ghost to mean "a workflow with no descriptor file that can neither be fixed nor deleted.") The parent workflow has no valid descriptor file, and it says I can refresh to fix that, but there is no refresh button. Funnily enough, it has a valid checker workflow. Neither can be published -- the main one because it has no valid descriptor, and the checker because checker workflows can't be published on their own.

This is not the same as #4437 -- that is about unpublishing a published ghost workflow and getting nonsensical errors. This is about an already-unpublished (possibly never published) ghost workflow which cannot be repaired nor deleted, which also happens to have a valid checker.

Valid PC-Air workflow that this ticket is **not** about: https://dockstore.org/workflows/github.com/DataBiosphere/analysis_pipeline_WDL/pc-air-wdl:v6.0.0?tab=info
Valid PC-Air's checker: https://dockstore.org/workflows/github.com/DataBiosphere/analysis_pipeline_WDL/pc-air-wdl_wdl_checker:v6.0.0?tab=info
Ghost PC-Air workflow (URL likely only works for me): https://dockstore.org/my-workflows/github.com/DataBiosphere/analysis_pipeline_WDL/pc-air
Ghost PC-Air's unpublished checker (URL likely only works for me): https://dockstore.org/my-workflows/github.com/DataBiosphere/analysis_pipeline_WDL/pc-air_wdl_checker

**Observations/Hunches**
* The repo is a multi-entry .dockstore.yml repo
* I have a hunch that this the ghost entry is a relic of an older version of a .dockstore.yml file, based on the names of everything involved.
  * Valid entry is named `pc-air-wdl`
  * Valid entry's checker is named `pc-air-wdl_wdl_checker`
  * Ghost entry is named `pc-air`
  * Ghost entry's checker is named `pc-air_wdl_checker`
  * [.dockstore.yml](https://github.com/DataBiosphere/analysis_pipeline_WDL/blob/c39984fe8f7202f360631f9d735ba7c3e2d2157f/.dockstore.yml#L58) gives name `pc-air-wdl`
* It's worth noting that Julian wrote this workflow, and #4437 and #4436 both had something to do with permissions. So this could be a permission issue, but I think the naming issue is more likely.

**To Reproduce (maybe)**
I don't know how the file was registered nor how long it's been ghostly, but I have a hunch this would do it:
1. Make a .dockstore.yml for a two workflow repo, giving each workflow a name (`foo` and `bar`)
2. Register checker workflows for both workflows
3. Change the name of `foo` to `foo-wdl` in the .dockstore.yml
4. See if `foo` exists as a ghost unpublished workflow that cannot be refreshed or removed

**Expected behavior**
* A workflow entry should maybe not be able end up without a valid descriptor file (this might not be realistic, especially since this seems to be caused by user error on my part)
* If a workflow somehow ends up without a valid descriptor file, even if it is my own fault, I should be able to repair it and/or completely delete it
* If a workflow goes ghostly due to a name change in a .dockstore.yml, Dockstore should be able to detect that there is a workflow that doesn't seem to be in a .dockstore.yml anymore and throw some sort of error telling me (eg, "Failed to find a workflow named `pc-air` in your .dockstore.yml", ideally with a suggestion as to what likely happened eg "was the `name:` field in the .dockstore.yml for this workflow modified?")

**Screenshots**
Ghost workflow
![Screen Shot 2022-09-20 at 10 12 05 AM](https://user-images.githubusercontent.com/27784612/191336178-f45f0712-f730-4eeb-800c-85902d222b8e.png)

Ghost workflow telling me to refresh, but there is no refresh button
![Screen Shot 2022-09-20 at 10 12 18 AM](https://user-images.githubusercontent.com/27784612/191336266-7c518cfe-a22e-4d86-9f96-4a4317f075d9.png)

Ghost workflow's valid checker:
![Screen Shot 2022-09-20 at 10 12 33 AM](https://user-images.githubusercontent.com/27784612/191337558-c3843ade-c049-4230-b9ff-7bb0347cf9c7.png)
![Screen Shot 2022-09-20 at 10 12 36 AM](https://user-images.githubusercontent.com/27784612/191337605-03f8c2ed-5ee1-4f72-9f62-51c0c00f97d1.png)

GitHub App logs: No errors except for known #4993 issue.
<img width="788" alt="Screen Shot 2022-09-20 at 11 42 56 AM" src="https://user-images.githubusercontent.com/27784612/191338970-ce33ce6e-a48e-4bde-bf27-c3103f5cea7b.png">

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.13.0) - 1.13.0

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.10.0) - 2.10.0

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.13.0) - 1.13.0

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.6) - 1.12.6

galaxyParsingLambdaVersion: 0.0.7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2248)
┆Fix Versions: Dockstore 1.14
┆Issue Number: DOCK-2248
┆Sprint: 105 - Colorado
┆Issue Type: Story

**Comment by kathy-t** [comment] 2023-01-30 15:51
After investigating, I was able to reproduce the error locally and on QA. The pc-air workflow became a "ghost" workflow because of this series of events:
- The `pc-air` workflow was renamed to `pc-air-wdl` in the .dockstore.yml. This created a new `pc-air-wdl` workflow. Note that changing the workflow name does not delete the old workflow, so the `pc-air` workflow still exists. 
- Somewhere along the way, all branches and/or tags containing a .dockstore.yml that referenced the `pc-air` workflow were deleted. This action resulted in the ghost `pc-air` workflow because when a branch or tag is deleted, Dockstore removes that version from the workflow. If there are no branches/tags referencing `pc-air`, then the `pc-air` workflow has no versions. The message that Ash saw in the Versions tab of the ghost workflow is actually meant for non-GitHub App workflows and is not accurate for GitHub App workflows that end up in this state. 
- The steps I followed to re-create the ghost workflow:
  - I already had a GitHub app workflow for a workflow named `foo`.
  - On GitHub, I created a new branch called ghost-workflow and I changed `foo` to `foo-wdl` in the .dockstore.yml. This created a new workflow called `foo-wdl` on Dockstore with one version called ghost-workflow.
  - I deleted ghost-workflow branch on GitHub. On Dockstore, the `foo-wdl` workflow is in the ghost state that Ash observed. It has no versions.

There are two solutions to this:
1) Automatically delete the GitHub app workflow if Dockstore detects that there are no versions for the workflow after a `DELETE branch/tag` event on GitHub.
    - Considerations: 
      - What if the user accidentally deleted the branch?
      - This can delete a published workflow if that published workflow only had one version which was deleted when the branch/tag was deleted
2) If there are no versions for a GitHub app workflow because it's a ghost workflow (went through the series of events above), display a more accurate description of the problem in the Versions tab. Something along the lines of `This GitHub app workflow has no versions because there are no branches/tags referencing this workflow. This is a result of the deletion of branches/tags that previously referenced this workflow. Modify your .dockstore.yml to reference this workflow to add a version.`
      a) An extension of option 2 is to allow the user to delete the GitHub app workflow in the UI via a `Delete` button if there are no Versions. This is getting into https://github.com/dockstore/dockstore/issues/1201 territory so it could be addressed in that ticket instead.

@coverbeck @denis-yuen any thoughts on which solution is preferred? I think I prefer 2 because the user would be informed about the problem

**Comment by denis-yuen** [comment] 2023-01-30 17:01
> * Somewhere along the way, all branches and/or tags containing a .dockstore.yml that referenced the `pc-air` workflow were deleted.

Wild! (Also, why we should definitely push snapshots more, but that's a side note) 

Think I prefer 2 (and agreed on 2a). 1 also may have strange interactions with snapshots and DOIs.

**Comment by coverbeck** [comment] 2023-01-31 17:18
> > * Somewhere along the way, all branches and/or tags containing a .dockstore.yml that referenced the `pc-air` workflow were deleted.
> 
> Wild! (Also, why we should definitely push snapshots more, but that's a side note)
> 
> Think I prefer 2 (and agreed on 2a). 1 also may have strange interactions with snapshots, DOIs. collections, ....

Also agreed, and nice detective work. I wonder if a variant of this happened with human-pangenomics, where there are a ton more workflows on Dockstore than are in the .dockstore.yml (at least the .dockstore.yml on master).

**Comment by denis-yuen** [comment] 2023-03-28 22:06
![Screenshot from 2023-03-28 18-06-16](https://user-images.githubusercontent.com/1730679/228377370-fb97d7d2-f893-494b-93d7-91f4d3547359.png)
Well,  wild edge case for the fix

**Closed** 2023-03-28 22:07 UTC
Labels: bug, web-service, review
