### ISSUE TITLE
Quickstart for MacOS has borked formatting

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4435] opened 2021-08-31 17:46 UTC
**Describe the bug**
<img width="1248" alt="Screenshot 2021-08-31 at 7 53 55 AM" src="https://user-images.githubusercontent.com/27784612/131525538-9a1af8f8-0d63-4c1f-8ae3-0c876ecb5092.png">

**To Reproduce**
https://dockstore.org/quick-start --> click MacOS

**Expected behavior**
Not this.

I attempted to fix this myself, but I can't spin up the dev server. 😞

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1897)
┆Issue Number: DOCK-1897
┆Sprint: Backlog
┆Issue Type: Story

**Comment by coverbeck** [comment] 2021-08-31 17:58
Thanks for pointing it out, but duplicate of #4417 .

**Closed by coverbeck** 2021-08-31 17:58 UTC
Labels: bug

**Comment by aofarrel** [comment] 2021-08-31 18:00
Oops... Sorry about that!
