### ISSUE TITLE
Galaxy workflow path regex and workflow path length

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3281] opened 2020-02-28 13:36 UTC
If you try and edit a galaxy workflow version, the save/update button is disabled. This is because it thinks the workflow path is invalid. I think this is likely due to the regex not testing for files ending in .ga

Also related somewhat, but I cannot set the workflow path when registering the workflow to be `/topics/genome-annotation/tutorials/annotation-with-prokka/workflows/Galaxy-Workflow-Workflow_constructed_from_history__prokka-workflow_.ga` because it is too long. Not sure if this is UI only or also in webservice.

https://github.com/dockstore/dockstore/issues/3186

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1243)
┆Issue Type: Story
┆Sprint: Sprint 30 Eel
┆Issue Number: DOCK-1243

**Comment by garyluu** [comment] 2020-02-28 15:06
Seems like max length in UI is 128 characters for workflow path.

**Comment by garyluu** [comment] 2020-02-28 15:09
Can't reproduce first issue

**Comment by denis-yuen** [comment] 2020-02-28 16:07
> Seems like max length in UI is 128 characters for workflow path.

That's not even a tweet anymore, time to expand!

**Comment by denis-yuen** [comment] 2020-02-28 16:10
I've got weirder issues, trying to get back to a previously registered workflow. 
galaxy-workflow-dockstore-example2/1 are both missing from the left but the wizard thinks the second is registered

![Screenshot from 2020-02-28 11-08-44](https://user-images.githubusercontent.com/1730679/75564819-d5bffc80-5a1a-11ea-9f79-4b09a4a6b58b.png)

**Comment by garyluu** [comment] 2020-02-28 16:20
I registered the 2nd one on mine...not sure if that useful information

**Comment by agduncan94** [comment] 2020-03-05 14:22
@garyluu If you registered it, then there exists a workflow with the path github.com/galaxy.../2, so this will show it as already created. I think what we need to do is add Denis as a user to these.

**Comment by denis-yuen** [comment] 2020-03-05 15:22
Yeah, I think we're past my issue and the path length issue due to the PR. 
If the regex is fixed, this can be closed

**Comment by garyluu** [comment] 2020-03-05 15:44
Clarification.  The regex thing was done and merged before this issue was even created (should still be tested though).  The only thing changed after this issue was created is the workflow path length.

**Comment by coverbeck** [comment] 2020-04-02 22:47
Verified that I was able to edit Galaxy workflow version in dev.dockstore.net environment, and that I was able to set the workflow path to that long value.

**Closed by coverbeck** 2020-04-02 22:47 UTC
Labels: bug, cli, gui, review
