### ISSUE TITLE
Descriptor file not found Nextflow workflow - gitlab

### ISSUE THREAD

**Issue by marcadella** [dockstore/dockstore#3599] opened 2020-06-23 09:09 UTC
**Describe the bug**
I imported a Nextflow workflow from my [Gitlab repo](https://gitlab.com/uit-sfb/metapipe) using the Quick register wizard. The repo contains `/nextflow.config` and it is the path defined in `Info/Workflow Path` but then when I navigate to `Files`, I get the following error message: `A Descriptor File associated with this workflow could not be found.`, which prevents me from creating a snapshot.
In addition, the `author` and `email` fiels remain empty even though `nextflow.config` contains an `author` field (on branch `master`).

**Expected behavior**
`/nextflow.config` should be found.

**Additional context**
 - UI version: 2.5.3
 - Webservice version: 1.8.6
 - host location: dockstore.org/

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1444)
┆Fix Versions: Dockstore 1.11
┆Issue Number: DOCK-1444
┆Sprint: Sprint 59- Hammerhead shark
┆Issue Type: Bug

**Comment by denis-yuen** [comment] 2020-06-23 14:33
Looks like a duplicate of https://github.com/dockstore/dockstore/issues/3314 
I was able to successfully register the workflow when uploading the same workflow to github

**Comment by Ldcabansay** [comment] 2020-08-26 00:34
Just tried replicating this issue, seems the gitlab API issue has been resolved and nextflow can find the main.nf descriptor now and the metadata fields for author and description are populating correctly. 

Caveat:  Dockstore DSL2 support is still in development, therefore the secondary .nf files imported using `include` are not yet added to files tab nor in the zip export.

**Comment by melainalegaspi** [comment] 2021-01-20 18:30
Need to double-check if this has been done already @denis-yuen

**Comment by denis-yuen** [comment] 2021-04-13 19:20
Functional on dev (and likely staging/prod)

![Screenshot from 2021-04-13 15-18-51](https://user-images.githubusercontent.com/1730679/114608457-b5c5b980-9c6b-11eb-91c9-f528aafd3a0c.png)
![Screenshot from 2021-04-13 15-18-54](https://user-images.githubusercontent.com/1730679/114608460-b65e5000-9c6b-11eb-898c-35e71fa22be8.png)

**Closed by denis-yuen** 2021-04-13 19:20 UTC
Labels: bug, hotfix-eligible, web-service
