### ISSUE TITLE
"Ghost" WDLs can be imported to Terra, but not other cloud partners

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4423] opened 2021-08-23 20:24 UTC
**Describe the bug**
If a dockstore.yml for an existing published workflow has an invalid link, Dockstore will correctly gray out buttons for DNAstack and DNAnexus as it correctly detects there is no valid WDL file to import. However, all Terra-related links will remain lit up.

**How I discovered this/How this can happen**
Dockstore parent entry: https://dockstore.org/workflows/github.com/aofarrel/checker-WDL-templates/tutorial-wf-with-optional-outputs:main?tab=info

I rearranged the checker template repository such that `outputs_all_required/` and `outputs_some_optional/` were placed inside a new folder. This rearrangement was all done in [this commit](https://github.com/aofarrel/checker-WDL-templates/commit/2ae7f0b272e52181d30dd986dd0675154de4cf52) but I forgot to update dockstore.yml so naturally it pointed to broken links.

Dockstore would not allow to import to some of our cloud partners, but I can make the attempt with all three flavours of Terra. Terra will throw a non-fatal "error loading WDL" popup on the right side of the screen but will still allow me to attempt to import into a new or existing workspace. After some loading symbols it will report the import failed (naturally).
![Screenshot 2021-08-23 at 1 12 15 PM](https://user-images.githubusercontent.com/27784612/130514035-958f345e-0bc3-4c97-b14b-1f842e6cd833.png)

**Expected behavior**
I should not be tempted by Terra to import a ghost WDL. The buttons should be grayed out like they are for other providers.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1891)
┆Issue Number: DOCK-1891
┆Sprint: Sprint 69- Tiger shark
┆Issue Type: Story

**Comment by coverbeck** [comment] 2021-09-03 17:47
I cannot reproduce and when I asked @aofarrel , he couldn't either. Closing.

@aofarrel If you see again, please reopen and please provide the URL where you see it. Thanks!

**Comment by aofarrel** [comment] 2021-12-16 00:40
I managed to find [another entry that does this](https://dockstore.org/workflows/github.com/gatk-workflows/gatk4-data-processing/processing-for-variant-discovery-gatk4:2.1.1?tab=files) and figured out a way to reproduce it!

1. Create and publish a repo via .dockstore.yml
2. [Break the .dockstore.yml by messing up the path that the descriptor file lives on](https://github.com/aofarrel/I-Will-Have-That-Power/commit/8a13b5d49cfcf01a51ae0cfd1e55abb0dedd97a1)
3. Your published dockstore entry will now seemingly allow you to import into Terra but not other cloud partners
<img width="1202" alt="Screenshot 2021-12-15 at 4 39 44 PM" src="https://user-images.githubusercontent.com/27784612/146286806-d16be09a-ad48-4c8c-b1b3-55bfd9aac238.png">

**Comment by coverbeck** [comment] 2022-03-01 00:20
Followed @aofarrel 's steps and it works for me on dev. Going to close, but Ash, if you have a chance and want to verify as well, that would be great -- the fix is so far only on dev.dockstore.net.

[Webservice](https://github.com/dockstore/dockstore/commits/23b4cad) - 23b4cad

[UI](https://github.com/dockstore/dockstore-ui2/commits/9a946ecb) - 2.8.5-135-g9a946ecb

[Compose Setup](https://github.com/dockstore/compose_setup/commits/5454f4a) - 5454f4a

[Deploy](https://github.com/dockstore/dockstore-deploy/commits/7c9a8a0) - 1.11.2.1-127-g7c9a8a0

galaxyParsingLambdaVersion: 0.0.4

**Closed by coverbeck** 2022-03-01 00:20 UTC
Labels: bug, gui, review
