### ISSUE TITLE
Nodes in DAG for galaxy workflows never filled with information

### ISSUE THREAD

**Issue by NatalieEO** [dockstore/dockstore#3402] opened 2020-04-16 16:46 UTC
**Describe the bug**
When you navigate to the DAG of a galaxy workflow, the nodes never have the info filled out when hovering over one. They are always TBD or N/A

**To Reproduce**
1. Go to https://dev.dockstore.net/workflows/github.com/NatalieEO/training-material:master?tab=info
2. hover over the nodes
3. See that all info is just TBD or NA

**Expected behavior**
I'd think some of it should be filled out

**Additional context**
API - 1.9.0-alpha.9-SNAPSHOT
UI - 2.5.1-rc.1-46-g37f122a0
dev.dockstore.net

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1314)
┆Issue Type: Story
┆Sprint: Backlog
┆Issue Number: DOCK-1314

**Comment by garyluu** [comment] 2020-04-16 19:27
Duplicate of https://github.com/dockstore/dockstore/issues/3271

**Closed by garyluu** 2020-04-16 19:27 UTC
Labels: bug
