### ISSUE TITLE
Cannot edit workflow version and set Workflow Path

### ISSUE THREAD

**Issue by wshands** [dockstore/dockstore#2836] opened 2019-08-30 23:52 UTC
## Bug Report
Cannot edit workflow version and set Workflow Path

### Expected behaviour
New Workflow Path is displayed in dialog

### Actual behaviour
Error message is displayed:
The webservice encountered an error.

[HTTP 413] OK: <html>
 <head><title>413 Request Entity Too Large</title></head>
 <body bgcolor="white">
 <center><h1>413 Request Entity Too Large</h1></center>
 <hr><center>nginx/1.13.1</center>
 </body>
 </html>
 
 
 
 
 
 

### Steps to reproduce the behaviour 
Go to https://staging.dockstore.org/my-workflows/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_wdl
Click on feature/freeze8-wdl on Versions tab
Click Edit link
Change Workflow Path to /variant-caller/variant-caller-wdl/topmed_freeze8_caller.wdl
Click Save Changes

### Environment (Browser or OS and Dockstore version)
https://staging.dockstore.org/api/static/swagger-ui/index.html#
https://github.com/dockstore/dockstore-ui2/releases/tag/2.4.0-rc.0
Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Mac OS Mojave 

![Screen Shot 2019-08-30 at 4 40 13 PM](https://user-images.githubusercontent.com/3650921/64056175-3fcc1780-cb46-11e9-8613-c1629daa2919.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-961)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-961

**Comment by denis-yuen** [comment] 2019-08-31 04:34
Probably  a duplicate of #2833

Also @wshands, please remove the template instructions

**Comment by coverbeck** [comment] 2019-09-02 06:03
I'm guessing it's the same API caused from a different place as in #2833; I wonder if it's worth creating an Angular interceptor to handle this instead updating all calls to this particular API. OTOH, these may be the only two calls, so maybe it's overkill.

**Comment by cricketsloan** [comment] 2019-09-11 13:45
➤ Gary Luu commented:

Much easier if someone has access to that repo reviews this instead.

**Comment by denis-yuen** [comment] 2019-09-11 14:20
@wshands could you invite @garyluu  to DataBiosphere?

**Comment by wshands** [comment] 2019-09-17 18:38
@garyluu you should get an email invite

**Comment by cricketsloan** [comment] 2019-09-17 21:32
➤ Gary Luu commented:

After creating another workflow with the same info and then changing the workflow path, I no longer get the error.

**Closed by cricketsloan** 2019-09-17 21:32 UTC
Labels: bug, gui, review
