### ISSUE TITLE
Cannot update organizations

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4014] opened 2021-01-25 23:33 UTC
**Describe the bug**
When going to update the BDC organization and fix its missing logo, I cannot make any changes to it; an error is thrown instead upon saving, even if no changes are made.

> [HTTP 500] OK: org.hibernate.exception.SQLGrammarException: could not extract ResultSet could not extract ResultSet ERROR: function lower(bytea) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Position: 582

**To Reproduce**
1. Go to https://dockstore.org/organizations/bdcatalyst
2. Click on the pencil icon to edit the organization page
3. Make no changes at all and click "update organization"
4. Get error

This doesn't seem to be caused by invalid input in some field because deleting all fields, or replacing them with something else, will throw the same error.

**Expected behavior**
Not that.

**Screenshots**
<img width="602" alt="within organization editor" src="https://user-images.githubusercontent.com/27784612/105779133-8f249c00-5f22-11eb-86bc-39527791bab9.png">

<img width="1256" alt="top of screen after closing organization editor" src="https://user-images.githubusercontent.com/27784612/105779148-98156d80-5f22-11eb-93fe-043857c4f8e3.png">

**Desktop (please complete the following information):**
 - OS: Catalina
 - Browser: Chrome

**Additional context**
Beth (UCSC) previously reported BDC's logo showing up as file-not-found but I can't find a ticket for it. Resolving this ticket's error so I can replace it with a different PNG will likely solve her ticket by proxy.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1694)
┆Issue Number: DOCK-1694
┆Sprint: Backlog
┆Issue Type: Story

**Comment by coverbeck** [comment] 2021-01-26 00:54
The UI is sending a request without a `name`. A `null` then gets passed to an HQL query starting [here](https://github.com/dockstore/dockstore/blob/756fd2e72ecd754ac44cd83bbbef0209b22526d1/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/OrganizationResource.java#L556). The SQL tries to `lower(null)`, which causes the above error.

**Comment by coverbeck** [comment] 2021-01-26 01:04
Looks like when you're editing, `form.value` on [this line](https://github.com/dockstore/dockstore-ui2/blob/9ddc6dcd09ba25df1caa6e1f324e193be56d366f/src/app/organizations/state/register-organization.service.ts#L78) does not have the name because it's not editable.

Also, [this line](https://github.com/dockstore/dockstore-ui2/blob/9ddc6dcd09ba25df1caa6e1f324e193be56d366f/src/app/organizations/state/register-organization.service.ts#L159) seems wrong.

**Comment by coverbeck** [comment] 2021-01-26 05:15
> Also, [this line](https://github.com/dockstore/dockstore-ui2/blob/9ddc6dcd09ba25df1caa6e1f324e193be56d366f/src/app/organizations/state/register-organization.service.ts#L159) seems wrong.

Mainly ignore this comment; status in the request is set to pending elsewhere, not on the line I linked to, and on top of that it is currently harmless (that field in the request is ignored by the web service). It irks me that the request doesn't reflect the actual org status, but it doesn't impact behavior.

**Comment by coverbeck** [comment] 2021-02-02 00:59
Confirmed this is fixed in staging.

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.10.1) - 1.10.1

[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.7.1) - 2.7.1

[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.1) - 1.1

[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.1) - 1.1

**Closed by coverbeck** 2021-02-02 00:59 UTC
Labels: bug, gui, review
