### ISSUE TITLE
Multiple workflows in the same repo might be unintentionally linked in some way

### ISSUE THREAD

**Issue by denis-yuen** [dockstore/dockstore#3296] opened 2020-03-04 22:31 UTC
**Describe the bug**
It seems that multiple workflows coming from one GitHub repo might be linked in some way. The symptom is that it appears that setting the default branch in one of the workflows might set the default branch in a different repo to the same default branch. 

**To Reproduce**
Not provided, might occur during refresh? Or when setting the default branch?

**Expected behavior**
Each workflow coming from the same repo should function completely independently.

**Additional context**
API - 1.8.1 (possibly earlier, not sure when this happened)
UI - 2.5.1
dockstore.org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1252)
┆Issue Type: Story
┆Sprint: Sprint 31 Flounder
┆Issue Number: DOCK-1252

**Comment by denis-yuen** [comment] 2020-03-04 22:37
Additional context: the change of the default branch might affect previously imported Terra workflows in some way. Conversation at https://databiosphere.slack.com/archives/CS2K5F7RV/p1582930390001700

**Comment by wshands** [comment] 2020-03-06 23:05
I cloned the skylab repo, registered three of the workflows, and changed the default branches a few times on each, but changing the default branch on one didn't affect the default branch on the others. Terra is not working properly right now so cannot test that interaction. So so far I cannot reproduce the bug. I'll have to keep working on this.

**Comment by coverbeck** [comment] 2020-03-06 23:15
Can you see what calls Terra is making to Dockstore on a page where it's not working? BTW, Terra seems to be up for me now.

**Comment by wshands** [comment] 2020-03-09 18:56
I used the Launch with Terra button to export my cloned Optimus workflow to a Terra workspace. I then changed the default branch on my other Optimus_test_LK workflow to a different default branch. I did not notice anything wrong with the Optimus workflow in Terra. I tried changing the workflow branch for the Optimus workflow in Terra but didn't notice any issues in either Dockstore or the Terra workspace. I tried a couple of other scenarios of changing default branches for the workflows in Dockstore but didn't notice any problem with the workflow in Terra.

**Comment by denis-yuen** [comment] 2020-03-12 16:14
From meeting: 
- confirmed that it seems like multiple workflows from one repo seemed to have branch switched
- not sure when it happened
- difficult to reproduce
- question on Terra as to whether it gets a copy when linked into a Terra workspace or whether it gets a copy
- all workflows seem t be switched to sb-snrnaseq-branch
- seems to occur across published and unpublished workflows
- seems to occur with workflows that have not been imported into Terra
- was updating space in Terra, will import latest copy of a workflow and update the default branch on Dockstore
- question as to whether the default branch changes what is being imported (seems like the user always has to select the branch being imported but it is best practice to switch the default branch for external users)
- demoed interaction between Terra and Dockstore
-

**Comment by denis-yuen** [comment] 2020-03-12 16:25
Question as to whether migration from draft-2 would affect 1.0
Need to test from production since Terra always imports from our production instance

**Comment by denis-yuen** [comment] 2020-03-12 16:29
Fri Feb 28 12:36:35 2020 -0500

**Comment by denis-yuen** [comment] 2020-03-12 16:36
One confusing interface choice: 
- can switch default branch, switch to public view then launch-with to import a specific version
- other option is to switch versions explicitly in the public view and then launch-with

There is a possibly unrelated Terra issue where importing the same workflow multiple times into Terra will cause both copies of a workflow to switch branch

**Comment by kbergin** [comment] 2020-03-13 18:59
Hi all,

I've learned today that a researcher who had cloned one of our workspaces in the past also found their workspace to be suddenly broken with this issue, even after we fixed the featured workspaces. This implies that anyone who has ever cloned our workspaces now has broken workspaces.

**Comment by coverbeck** [comment] 2020-03-19 00:16
Sorry for the belated update. Here is what I have so far. 

1. The Dockstore UI effectively has the concept of an implicit default version. If the workflow owner does not explicitly set the default version, the UI defaults to the most recently updated version. This means if you refresh a workflow whose default version is not set, the next time you view the workflow, the implicit default might be different.
   1. I suggest Terra explicitly set the default version for all public workflows.
   2. Dockstore could enforce an explicit default version going forwards, and either not allow publishing of a workflow without a default version, or explicitly set it when publishing if not set.
2. Any member of a GitHub org or repo can refresh the workflows associated with that GitHub org/repo. A non-Broad member of the HCA GitHub organization refreshed their Dockstore workflows on Feb 27. This caused the HumanCellAtlas workflows to get refreshed and the implicit default versions for some workflows to change per item 1.
    * This is the intended behavior by Dockstore, but I can see how it would be confusing if you didn't know that somebody else the workflow. Our goal is to move workflows to GitHub apps starting in 1.9, so refresh won't even be necessary, and this should be rendered moot.
3. Terra was displaying an error message when viewing a workflow saying "You do not have access to this workflow...". [Image](https://databiosphere.slack.com/files/U91T6HWDA/FUCTUGBDX/image__19_.png) (may require Slack access). We did not discuss this one at our meeting as we ended up getting into what are items 1 and 2. Based on the screenshot I feel like this one is on the Terra side -- even though numbers 1 and 2 can lead you into importing the wrong version, the Terra should be pointing at a specific version, and as long as the version exists it should work. We need more info on this one. Is there still a user that has the problem? Can we get them to open their browser dev tools and see what network calls and/or console errors are happening?

**Comment by kbergin** [comment] 2020-03-19 14:01
I'm not aware of a workspace that still has the issue, but if I find one I'll share. Will you be coordinating with Terra team to complete the recommendations and debug the remaining issue (3)?

**Comment by coverbeck** [comment] 2020-03-19 16:20
> Will you be coordinating with Terra team to complete the recommendations and debug the remaining issue (3)?

I'll first try to find it your source code to see what it is doing; then I'll reach out to the Terra team on the Slack channel, and/or I may need your help in getting in touch with the right people.

Thanks.

**Comment by coverbeck** [comment] 2020-03-25 22:51
Closing this ticket. As described three comments above, the org was refreshed by a user, which had the affect of refreshing all workflows. There is no bug we could find in the logs, code or testing where refreshing one workflow affected other workflows.

Spun off #3345 as a usability issue that research revealed. The issue with Terra not being able to display a particular workflow has been moved to a Slack discussion, and if it turns out to be a Dockstore issue, will log that separately.

**Closed by coverbeck** 2020-03-25 22:51 UTC
Labels: bug, gui, web-service
