### ISSUE TITLE
Figure out how much we use paths as unique IDs

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2601] opened 2019-07-04 15:01 UTC
This stems from workflows and services using the same path, so if you have a workflow with path a/b/c, you cannot add a service with a/b/c.

This ticket would involve looking for what parts of the code depend on the path (full_workflow_path/tool_path) being unique.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-805)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 16 Pram
┆Issue Number: DOCK-805

**Comment by denis-yuen** [comment] 2019-07-31 18:59
@coverbeck think this is a duplicate

**Comment by cricketsloan** [comment] 2019-08-05 16:07
➤ Charles Overbeck commented:

Closing this as a duplicate of https://ucsc-cgl.atlassian.net/browse/SEAB-339 ( https://ucsc-cgl.atlassian.net/browse/SEAB-339|smart-link ) and (partially) DOCK-826.

**Closed by cricketsloan** 2019-08-05 16:07 UTC
Labels: gui, web-service
