### ISSUE TITLE
Unable to delete a self-created tool

### ISSUE THREAD

**Issue by ByteMap** [dockstore/dockstore#2884] opened 2019-09-11 22:35 UTC
### Expected behaviour

Tool deletes when delete button on My Tools page is clicked

### Actual behaviour

- Error Message 'Encountered problems deleting tools' pops up when deleting
- When going on inspect mode, deleting results with an Error 500 in the console
- Error 500 results in message: **Could not convert Dockstore entry to Elasticsearch object**

<img width="345" alt="Screen Shot 2019-09-11 at 3 01 00 PM" src="https://user-images.githubusercontent.com/42463687/64738763-0203b300-d4a5-11e9-9ec4-c055ad702233.png">

<img width="544" alt="Screen Shot 2019-09-11 at 2 41 52 PM" src="https://user-images.githubusercontent.com/42463687/64738731-e5677b00-d4a4-11e9-8374-0d0aedce3ace.png">

### Steps to reproduce the behaviour 

1. Go to My Tools page
2. Have a tool of any kind
3. Select the tool and click on the delete button

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-992)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.8
┆Issue Number: DOCK-992

**Comment by denis-yuen** [comment] 2020-01-15 19:44
Still alive, seems to be independent from DB migration issue. 
Not going to consider this blocking for 1.8.0 release

**Comment by agduncan94** [comment] 2020-01-17 14:23
Saw an error when trying to delete a gitlab tool. I also tested deleting a quay and amazon tools and that worked fine.
The error I saw was 

> ERROR SyntaxError: Unexpected token u in JSON at position 0

Saw on 1.8.0-beta.9 and 2.5.0-beta.3

**Comment by coverbeck** [comment] 2020-01-22 17:30
1. Does the Gitlab tool issue also occur on production or is this a regression?
2. The events error seems like a broader issue that  @agduncan94 , @david4096 and @wshands should discuss for deletion/archiving. I guess it means we either only do soft deletes or we have have to remove entries from the events table as well.

**Comment by agduncan94** [comment] 2020-01-22 18:15
@coverbeck I also see it on prod.

**Comment by agduncan94** [comment] 2020-01-23 21:09
Closing this as it is now at https://github.com/dockstore/dockstore/issues/3171

**Closed** 2020-01-23 21:09 UTC
Labels: bug, review, web-service
