### ISSUE TITLE
My Services accordion is occasionally empty

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#2741] opened 2019-08-12 19:36 UTC
Sometimes when you go to my-services page the accordion will be empty (besides title) and there will be no published/unpublished tabs. Will add screenshot if I can reproduce.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-891)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7.x
┆Sprint: Seabright Sprint 18 Skipjack
┆Issue Number: DOCK-891

**Comment by garyluu** [comment] 2019-08-19 14:18
Is it possible the accordion was just collapsed?

**Comment by agduncan94** [comment] 2019-08-19 15:51
@garyluu No it was not.

**Comment by garyluu** [comment] 2019-09-05 19:02
Managed to reproduce this a total of one time.  Some observations:

The accordion is not expanded. Trying to expand it, causes it to immediately collapse. Other panels seem to workflow fine.

**Comment by denis-yuen** [comment] 2019-09-05 20:23
Lowering priority to 1.7.x, if this is so hard to reproduce I'm ok with it being a potential hotfix

**Comment by garyluu** [comment] 2019-10-07 15:31
To kind of consistently reproduce (on my machine) while developing.  Open 10 tabs to /my-tools .  Change anything in the code to trigger a refresh on all tabs (because of watch).

**Comment by Ldcabansay** [comment] 2019-12-16 21:00
Might be fixed? Tried a bunch to reproduce and seems okay...maybe. Closing this and hoping it doesn't come back. 
API - 1.8.0-alpha.2
UI - 2.5.0-alpha.0

**Closed by Ldcabansay** 2019-12-16 21:00 UTC
Labels: bug, gui, review
