### ISSUE TITLE
When looking at a tool the second nav bar says available tools, but it should say Tool Details

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#1249] opened 2018-03-28 14:35 UTC
Go to any published tool on dockstore. The second navbar says Available Tools. This is what it should say on the Tools page, but not when viewing an individual tool. It used to be Tool Details, we should go back to this. Same for workflows.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-320)
┆Issue Type: Story
┆Fix Versions: Dockstore 2.X
┆Issue Number: DOCK-320

**Comment by denis-yuen** [comment] 2019-08-30 15:38
Duplicate of #2532

**Closed by denis-yuen** 2019-08-30 15:38 UTC
Labels: gui
