### ISSUE TITLE
Refresh organization with GitHub App workflows - confusing 400 error UX

### ISSUE THREAD

**Issue by GFJHogue** [dockstore/dockstore#3980] opened 2020-12-15 19:31 UTC
**Describe the bug**
https://discuss.dockstore.org/t/cannot-refresh-dockstore-yml-workflows/4066
When refreshing an org with a GitHub App (.dockstore.yml) workflow, the user gets a red 400 error notification.
```
warning The webservice encountered an error.
[HTTP 400] OK: Cannot refresh .dockstore.yml workflows
```
The notification is red, indicating that something is wrong - even though it is expected behavour to not refresh these workflows.

**Expected behavior**
Shouldn't show a red `error`, but rather a more "info"-level notification.

**Screenshot**
![400gha](https://user-images.githubusercontent.com/5513934/102262924-a9119e80-3ee1-11eb-83d3-9cab639d9b80.png)

**Additional context**
[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.10.0) - 1.10.0
[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.7) - 2.7
Host - Prod

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1674)
┆Issue Number: DOCK-1674
┆Sprint: Backlog
┆Issue Type: Story

**Comment by coverbeck** [comment] 2020-12-15 21:36
I think the the UI should  just skip refreshing .dockstore.yml workflows.

Maybe some sort of indicator that the workflow is not manually refreshable? Or a more subtle warning (snackbar?) if org has .dockstore.yml workflows.

**Comment by NatalieEO** [comment] 2020-12-15 21:42
this is a dupe of #3811

**Closed by NatalieEO** 2020-12-15 21:42 UTC
Labels: bug, gui

**Comment by GFJHogue** [comment] 2020-12-15 22:07
Whoops, I must have typoed my search to miss that
