### ISSUE TITLE
Checkstyle 8.28

### ISSUE THREAD

**Issue by garyluu** [dockstore/dockstore#3469] opened 2020-05-12 14:26 UTC
**Is your feature request related to a problem? Please describe.**
Checkstyle.xml doesn't seem to work when checkstyle version is set to 8.28 or higher

**Describe the solution you'd like**
Checkstyle.xml to be modified so that it works for newer versions

**Describe alternatives you've considered**
Just use the 
```
<groupId>com.coveo</groupId>
<artifactId>fmt-maven-plugin</artifactId>
```
for most of the formatting instead and keep checkstyle.xml minimal

**Additional context**
Kept getting
```
The Checkstyle rules file could not be parsed.
				cannot initialize module TreeWalker - cannot initialize module JavadocMethod - Property 'logLoadErrors' does not exist, please check the documentation
```
was confused

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1362)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 39 Narwhal
┆Issue Number: DOCK-1362

**Comment by GFJHogue** [comment] 2020-07-13 14:55
Checked checkstyle [8.28 release notes](https://checkstyle.sourceforge.io/releasenotes.html#Release_8.28) and found the cause of the above error https://github.com/checkstyle/checkstyle/issues/7329 (`logLoadErrors` & `suppressLoadErrors ` were removed).
Then I discovered that this has already been fixed by @denis-yuen in https://github.com/dockstore/dockstore/commit/566041807c884540ed1a43ffbead45d9f2deddc9 and we're currently on checkstyle 8.29 https://github.com/dockstore/dockstore/blob/develop/pom.xml#L932

In this case, shall I upgrade us to the latest (8.34)?

**Comment by garyluu** [comment] 2020-07-13 18:08
I might've been working on the hotfix branch at that time

**Comment by GFJHogue** [comment] 2020-07-13 18:36
Closing because not an issue

**Closed by GFJHogue** 2020-07-13 18:36 UTC
Labels: enhancement, web-service
