### ISSUE TITLE
dockstore --upgrade doesn't work

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#3626] opened 2020-06-29 21:21 UTC
_If this is the wrong place to put tickets for the CLI let me know and I'll move it._

If you upgrade the dockstore CLI, it doesn't "stick" and you'll continue to get errors every time you use a dockstore command.

**dockstore --upgrade**
> 14:11:43.284 [main] ERROR io.dockstore.client.cli.ArgumentUtility - Current version : 1.8.0
> 14:11:43.287 [main] ERROR io.dockstore.client.cli.ArgumentUtility - Latest version : 1.8.5
> 14:11:43.287 [main] ERROR io.dockstore.client.cli.ArgumentUtility - You do not have the most recent stable release of Dockstore.
> Please upgrade with the following command:
>    dockstore --upgrade
> Current Dockstore version: 1.8.0
> Upgrading to most recent stable release (1.8.0 -> 1.8.5)
> Download complete. You are now on version 1.8.5 of Dockstore.

**dockstore --version**
> 14:11:54.846 [main] ERROR io.dockstore.client.cli.ArgumentUtility - Current version : 1.8.0
> 14:11:54.849 [main] ERROR io.dockstore.client.cli.ArgumentUtility - Latest version : 1.8.5
> 14:11:54.849 [main] ERROR io.dockstore.client.cli.ArgumentUtility - You do not have the most recent stable release of Dockstore.
> Please upgrade with the following command:
>    dockstore --upgrade
> Dockstore version 1.8.0
> The latest stable version is 1.8.5
> Please upgrade with the following command:
>    dockstore --upgrade

I'm wondering if this bug only exists on OSX 10.15, which is what I'm using. I don't know a lot about PATH on zsh but I have heard there's some differences.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-1466)
┆Issue Type: Story
┆Sprint: Backlog
┆Issue Number: DOCK-1466

**Comment by denis-yuen** [comment] 2020-06-29 21:25
This is a duplicate of https://github.com/dockstore/dockstore/issues/3426

> If this is the wrong place to put tickets for the CLI let me know and I'll move it.

No worries, this is the right place

**Closed** 2020-06-29 21:26 UTC
Labels: bug
