### ISSUE TITLE
Consecutive releases on GitHub not always making it to Dockstore

### ISSUE THREAD

**Issue by agduncan94** [dockstore/dockstore#3689] opened 2020-07-23 19:09 UTC
**Describe the bug**
A user had our GitHub app installed on a repository on 2020-07-23. They made 2 consecutive releases within about 30 seconds of each other (11:17:27am and 11:17:59am), and only the first release made it in. After waiting for a period of time and then trying again, they were able to get the second release in (11:22:08).

Looking at the code, seems like the second release failed with the following
```
! at io.dockstore.webservice.helpers.GitHubSourceCodeRepo.getDockstoreYml(GitHubSourceCodeRepo.java:769)
```

**To Reproduce**
1. Install our github app
2. Add a .dockstore.yml to a repository
3. Make two successive releases
4. Second release may not be recorded on Dockstore.

**Expected behavior**
Both releases should have made it in (assuming they both had valid dockstore.yml files)

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-1511)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.9.X
┆Sprint: Sprint 44- Sea Horse
┆Issue Number: DOCK-1511
┆Epic: Automated sync of Dockstore and GitHub apps

**Comment by coverbeck** [comment] 2020-09-10 22:02
Unproven hypothesis: may be fixed by #3782

**Comment by GFJHogue** [comment] 2020-09-22 18:48
Still an issue. In my 2 attempts it was easy to reproduce with consecutive GitHub releases.

```
ERROR	Error handling GitHub webhook, will not retry: 418 - User GFJHogue: Error handling push event for repository GFJHogue/one-workflow-many-ways and reference refs/tags/0.0.5
Could not retrieve .dockstore.yml. Does the tag exist and have a .dockstore.yml?
```

@coverbeck hypothesis disproven

**Comment by coverbeck** [comment] 2020-09-22 19:59
> hypothesis disproven

Bummer, but at least you can reproduce.

**Comment by GFJHogue** [comment] 2020-09-24 20:36
Spent some time trying to reproduce the issue locally with integration tests:
- pinged the webservice with consecutive releases
- concurrently pinged the webservice with simultaneous releases

My attempts were unsuccessful.

It appears more and more like the issue may be something on GitHub's end where we end up hitting a race condition where we fail to read `.dockstore.yml` for the subsequent releases (we don't retry in this case).

In this case, we would require some sort of workaround to allow Lambdas calls with 418's to wait and retry (perhaps allow them to requeue X number of times by tracking retries in the SQS message, or have a separate SQS queue...)

**Comment by GFJHogue** [comment] 2020-09-24 21:00
Adding SQS queue delay may work too...

**Comment by coverbeck** [comment] 2020-09-25 00:45
> In this case, we would require some sort of workaround to allow Lambdas calls with 418's to wait and retry (perhaps allow them to requeue X number of times by tracking retries in the SQS message, or have a separate SQS queue...)

The 418 tells the lambda not to retry. So another option is to not return a 418 in this case. We had a discussion in Slack about 418s, where it turns out the web service is incorrectly returning 418 for all error cases. The conclusion of which I was going to log a ticket that the web service shouldn't always always return a 418. Which apparently I forgot to do, because I can't find it... On our Slack, search for the text "I think it was supposed to be dependent on the exit code" (I don't want to post the link to the channel here, since it's not public).

Looking at [the lambda code](https://github.com/dockstore/lambda/blob/55d779e5ac193e55168f8e2c265a93ebd45186b8/upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js#L207), we would need to return a 5xx for it to retry.

**Comment by GFJHogue** [comment] 2020-09-25 15:08
I had success raising the SQS Delivery delay. From trial/error 30-60 seconds seems relatively safe. This also validates my suspicions of GitHub slowing down in these instances. I'll make a CloudFormation PR as the solution for this issue.

Regarding your point @coverbeck , the issue with "not returning 418 in this case" is that it would be very quite difficult to figure out from the webservice's perspective whether
- the user doesn't have a `.dockstore.yml` for that tag (don't retry, user's fault), or
- GitHub hasn't yet updated (we never get the release)

**Comment by coverbeck** [comment] 2020-09-25 16:21
Cool findings.

1. Suggest we target this for a hotfix.
2. Did not realize that we couldn't distinguish this failure from a legit failure, so yes you're right. But I went ahead and created a ticket, the one I should have already created, for other cases where we could signal to retry, #3830

**Comment by NatalieEO** [comment] 2020-09-30 22:32
Confirmed two consecutive GItHub releases appeared on staging 

API - 1.9.2-SNAPSHOT

UI - 2.6.1-7-gc9f59c24

and develop

Webservice - 91eff72

UI - 2.6.1-46-g23d6e519

Compose Setup - 6c50698b903981ca78f05759cc2c3a7049e847a6

Deploy - 1.9.2-33-gda01baf

**Comment by coverbeck** [comment] 2020-09-30 23:34
I don't think staging has this fix deployed. Not sure this was verified correctly. How quickly did you push the releases? @GFJHogue how close do the releases need to be to each other?

**Comment by NatalieEO** [comment] 2020-09-30 23:58
Probably released within 5 seconds of each other.

**Comment by coverbeck** [comment] 2020-10-01 00:07
Hmm, interesting. I went and checked and don't see the fix deployed on staging. I wonder how Greg reproduced and frequently the error happened.

**Comment by GFJHogue** [comment] 2020-10-01 14:43
@coverbeck Hmm, this is strange.
The SQS & Lambda that are named "staging" seem to have been inactive since June (according to logs & monitoring).
Where is staging getting its GitHub App events from?

**Comment by coverbeck** [comment] 2020-10-01 16:10
Discussed with Greg and turns out it was deployed on staging -- I was looking in the wrong place. Closing; sorry for the confusion.

**Closed by coverbeck** 2020-10-01 16:10 UTC
Labels: bug, lambda, review
