### ISSUE TITLE
CWL parent hints should not override child hints

### ISSUE THREAD

**Issue by svonworl** [dockstore/dockstore#4662] opened 2022-01-14 00:22 UTC
**Describe the bug**
To understand this bug, make sure you understand the concept of CWL hints and requirements.  See the CWL 1.2 spec, section 3.3:
https://www.commonwl.org/v1.2/Workflow.html#Requirements_and_hints
Hints and requirements are specified in the CWL file, and we parse them to determine the dockerPull for each tool.  Hints and requirements can be specified for a workflow, tool, or a workflow step.

The CWL spec says that:

> Requirements specified in a parent Workflow are inherited by step processes if they are valid for that step. If the substep is a CommandLineTool only the InlineJavascriptRequirement, SchemaDefRequirement, DockerRequirement, SoftwareRequirement, InitialWorkDirRequirement, EnvVarRequirement, ShellCommandRequirement, ResourceRequirement are valid.
[...]
> If the same process requirement appears at different levels of the workflow, the most specific instance of the requirement is used, that is, an entry in requirements on a process implementation such as CommandLineTool will take precedence over an entry in requirements specified in a workflow step, and an entry in requirements on a workflow step takes precedence over the workflow. Entries in hints are resolved the same way.
> 
> Requirements override hints. If a process implementation provides a process requirement in hints which is also provided in requirements by an enclosing workflow or workflow step, the enclosing requirements takes precedence.

In other words, requirements and hints propagate downwards into the workflow tree, child requirements override parent requirements, child hints override parent hints, and if both exist at a particular juncture, requirements override hints.

However, in the absence of requirements, the logic in CWLHandler.getContent causes a parent hint to override a child hint.

**To Reproduce**
1. Manually register the CWL workflow repo https://github.com/svonworl/hint-over-hint-cwl
2. Select the Tools tab
3. Both tools should have the dockerPull 'child', since there are hints in child.cwl.
4. However, one tool has the dockerPull of the parent workflow step.

**Expected behavior**
A child hint should override a parent hint.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2033)
┆fixVersions: Dockstore 1.13
┆friendlyId: DOCK-2033
┆sprint: 87 Octocat
┆taskType: Story

**Comment by coverbeck** [comment] 2022-10-11 00:19
Confirmed that the tools tab is now behaving as expected.

I did notice that the DAG page looks a tad odd; there is an End circle with nothing pointing to it. Go to the DAG tab on this workflow: https://staging.dockstore.org/my-workflows/github.com/coverbeck/hint-over-hint-cwl

At a glance, other CWL workflows I look at have the End circle with one or more arrows pointing to it.

I know this was a test workflow to help test the hints problem, so perhaps it's OK, but since my CWL knowledge is minimal, I wanted to @svonworl to confirm this is OK before closing.

**Comment by svonworl** [comment] 2022-10-11 16:51
> I know this was a test workflow to help test the hints problem, so perhaps it's OK, but since my CWL knowledge is minimal, I wanted to @svonworl to confirm this is OK before closing.

Whenever I modify the CWL code, I try to maintain the current behavior when possible.  This particular workflow didn't define any inputs/outputs, so the End circle isn't linked by arrows.  One could argue that if that's the case, the Start circle shouldn't have any links to the intermediate steps.  However, I'm not sure the latter is worth fretting over, because, as far as I know, all useful real-world workflows (that define inputs and outputs) render correctly.

**Comment by coverbeck** [comment] 2022-10-11 20:40
Logged #5173 just in case. Closing this one as done.

**Closed by coverbeck** 2022-10-11 20:40 UTC
Labels: bug, web-service, review
