### ISSUE TITLE
Investigate BAMStats convert problem

### ISSUE THREAD

**Issue by emlys** [dockstore/dockstore#2863] opened 2019-09-09 19:18 UTC
Running `dockstore tool convert entry2json --entry quay.io/collaboratory/dockstore-tool-bamstats:1.25-6_1.0 > Dockstore.json` as directed here https://staging.dockstore.org/containers/quay.io/collaboratory/dockstore-tool-bamstats:1.25-6_1.0?tab=launch does not work as expected. In the resulting Dockstore.json, each input key is prefixed with 'BAMStats', e.g. 
"BAMStats/bam_input": {...}.  This causes an error when using this file as an input because an input field called just "bam_input" is expected. The prefixes have to be removed in order for it to run.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-980)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.9
┆Sprint: Seabright Sprint 29 Dugong
┆Issue Number: DOCK-980

**Comment by denis-yuen** [comment] 2019-09-10 17:37
It sounds a regression

**Comment by agduncan94** [comment] 2019-09-17 13:14
This seems to be an issue with the version of cwltool. It worked with 1.0.20180403145700, but didn't when I updated to 1.0.20190915164430

**Comment by agduncan94** [comment] 2019-09-17 13:58
CWL avro takes the id string of an input/output and retrieves everything that occurs after the last # and uses that as the key in the run JSON.  Below is a sample id field for an input mem_gb
```
"id": "file:///tmp/1568727217812-0/Dockstore.cwl#BAMStats/mem_gb"
```

You can see that the id is prefixed by BAMStats. This must be a new thing done by cwltool.

One option is to edit the CWL avro to remove the tool/workflow id from the id string. Another option is to edit Dockstore code, though this would be less elegant.

**Comment by denis-yuen** [comment] 2019-09-17 14:27
Sounds like updating CWL avro makes sense.
I'm going to tentatively schedule for `1.7.x` 
Alternatively, we can recommend `cwltool --make-template`

**Comment by agduncan94** [comment] 2019-09-18 15:06
I like the idea of also suggesting `cwltool --make-template`,  but first we should properly explain the difference between that and our approach (especially including outputs). Should I make a ticket for it?

**Comment by denis-yuen** [comment] 2019-09-18 17:18
Oh right, that's true. Yeah, I think it would be a ticket then

**Comment by agduncan94** [comment] 2019-09-18 17:42
https://github.com/dockstore/dockstore/issues/2910

**Comment by agduncan94** [comment] 2019-09-19 13:29
@denis-yuen moving this to 1.7.x

**Comment by denis-yuen** [comment] 2020-01-03 18:55
1. Needs new version of cwlavro to be released
2. Needs new version of cwlavro to be used in Dockstore

**Comment by agduncan94** [comment] 2020-02-28 14:25
Confirmed that this is working now on staging (API 1.8.1)

**Closed** 2020-02-28 15:27 UTC
Labels: bug, cli
